Vagrant.configure("2") do |config|

    config.vm.define "ahors" do |master|
        config.vm.box = "debian/bookworm64"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.hostname = "ahorsS"

        master.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
            vb.name = "ahorsS"
        end
     
        # Provision Ansible
        master.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "./ansible/provision.yml"
          ansible.inventory_path = "./ansible/inventory.ini"
        end
    end
end
